dropbox/dropbox-sdk-js

examples/index.html
examples/node/upload.js
examples/upload/index.html
generator/generate_routes.py
src/dropbox-base.js
src/dropbox.js
src/routes.js
src/upload-request.js
test/upload-request.js

WIP: Add preliminary content upload request

---

examples/download/index.html
examples/index.html
examples/node/download.js
examples/node/upload.js
examples/upload/index.html
generator/generate_routes.py
src/download-request.js
src/dropbox-base.js
src/dropbox.js
src/routes.js
src/upload-request.js
test/download-request.js
test/upload-request.js

@braincore this is a mostly working solution. the major issue here is that superagent puts the binary response in `response.text` and when you create a blob from that, it itsn't working. You can try it with the download example.

Implement file download methods

---

examples/auth/index.html
examples/basic/index.html
examples/download/index.html
examples/index.html
examples/styles.css
examples/team-as-user/index.html
examples/team/index.html
examples/upload/index.html

This improves the examples in several ways:
- basic styles
- inputs instead of alerts
- autocomplete for tokens in inputs
- better description on how to get a token
- easier navigation between examples
This fixes:
#47, #49 and #48

Improve examples

---

package.json
src/routes-team.js
src/routes.js
src/types.js
test/dropbox-team.js

Pull in latest spec and stone code, generate new SDK, and bump up version number.
Addresses https://github.com/dropbox/dropbox-sdk-js/issues/103

Reflect updated spec with Paper API

---

src/rpc-request.js

Return error as object instead of string

---

docs/README.md
src/dropbox-base.js
test/dropbox-base.js

This pull request contains a new method to simply the authentication process for Cordova and PhoneGap applications. This feature is available in version 1 of the API, but there is no official implementation in version 2. This is my proposition of an official implementation with tests and documentations.
Issue #115

Issue #115: Cordova / PhoneGap application authentication process

---

package.json

Dropbox use a vulnerable dependency **qs** (through *superagent*)
See https://snyk.io/vuln/npm:qs:20170213
This PR update **superagent** to the latest version **3.5.2**
Thank you.

Update superagent dep

---

package.json

Added build conf. to NPM package

---

examples/javascript/upload/index.html

Adding example for upolading files that are bigger than 150 Mb using filesUploadSession* methods.

Adding filesUploadSession* API example

---

conf.json
docs/README.md
docs/tutorials/Authentication.md
docs/tutorials/Getting started.md
docs/tutorials/Installation.md
docs/tutorials/JavaScript SDK.md
package.json

- updated all links to redirect to the website.
- moved configuration parameters for jsdoc to `conf.json`

moved jsdoc params to config file; updated all links to website

---

src/dropbox-base.js

Fixes https://github.com/dropbox/dropbox-sdk-js/issues/64

Fix getAccessTokenFromCode for null redirectUri

---

src/dropbox-base.js
test/dropbox-base.js

- Add option for requesting specific scopes and including already granted scopes in oauth flow
- Add support for requesting specific scopes on token refresh

Add support for Scopes

---

examples/javascript/PKCE-backend/code_flow_example.js
examples/javascript/PKCE-backend/package-lock.json
examples/javascript/PKCE-backend/package.json
examples/javascript/simple-backend/package-lock.json
package-lock.json
package.json
rollup.config.js
src/dropbox-base.js
src/dropbox.js
src/team/dropbox-team.js
test/download-request.js
test/rpc-request.js
test/upload-request.js

* Add PKCE support in oauth flow
* Remove necessity for secret in refresh flow
* Update Tests
* Add PKCE backend example

Add support for PKCE

---

.github/workflows/documentation.yml

Fix name of documentation action

---

.github/workflows/npm_upload.yml

remove registry from npm setup

---

.github/workflows/npm_upload.yml

Move publish to github action

---

.github/pull_request_template.md
.github/workflows/documentation.yml
.github/workflows/npm_upload.yml
package.json

Fix publish

---

package.json

Update to 6.0.1

---

UPGRADING.md
package-lock.json
package.json
src/auth.js
src/dropbox.js

- Update files to include in distributable
- Bind window to fetch function
- Bump version to 6.0.2
- Add DropboxResponse translation to upgrading
**Validation**

Misc Bug Fixes

---

.github/ISSUE_TEMPLATE/question_help.md

Fix type in question_help template

---

types/dropbox_types.d.ts
types/index.d.ts

Automated Spec Update 
333278e77e8104e31e544aecac5338a350537ed5 
* Add basic files
* Forgot to save readme
* Add logo to readme
1050a44f7793bd5546db8aed197602ad763466e4 
Check Namespace:
- Update comments for auth tests
Remove Cloud_Docs Namespace
File Request Namespace:
- Add optional description parameter to FileRequest, CreateFileRequestArgs, and UpdateFileRequestArgs structs
Files Namespace:
- Add operation_suppressed type to WriteError union
- Update Comments
Shared Links Namespace:
- Update Comments
Sharing Files Namespace:
- Update Comments
Sharing Folders Namespace:
- Update Comments
Team Legal Holds Namespace:
- Add invalid_date to LegalHoldsPolicyCreateError union
Team Log Generated Namespace:
- Add BackupStatus union
- Add PolicyType union
- Add data_governance and remove …

Automated Spec Update

---

UPGRADING.md
examples/javascript/README.md
lib/routes.js
package.json
scripts/release_note_generator.sh
src/dropbox.js
src/response.js
types/dropbox_types.d.ts
types/index.d.ts

- Add extension to import fixing (#258)
- Update no arg routes to not require `null` closing (#41)
- Add base64 removing dependency on Buffer closing (#176)
- Update Javascript example readme to link to valid paths and commands
**Validation**

Add extension to import, update no arg routes to not require `null`, add base64 function to remove Buffer, update readme for examples

---

.github/workflows/spec_update.yml

Update Trigger for Spec Update action

---

generator/generate_routes.py
lib/routes.js
package.json
types/index.d.ts

Add flag to generate routes to wrap return types

---

package.json

Update version for spec update

---

generator/typescript/index.d.tstemplate
package-lock.json
test/types/.eslintrc
test/types/types_test.js
test/types/types_test.ts
types/index.d.ts

- Add typed properties to definitions and generator
- Add tests to validate these fields remain accessible
- Fix for [#385](https://github.com/dropbox/dropbox-sdk-js/issues/385)
**Validation**

Add properties to DropboxResponse type definitions

---

package.json

Bump version for type fix

---

generator/typescript/index.d.tstemplate
src/error.js
src/response.js
test/types/.eslintrc
test/types/types_test.js
test/types/types_test.ts
test/unit/dropbox.js
test/unit/error.js
test/unit/response.js
types/index.d.ts

- Fix for [#278](https://github.com/dropbox/dropbox-sdk-js/issues/278)
**Validation**

Change error response handling to jsonify error

---

UPGRADING.md
package.json

Update to version v8.0.0 and add Upgrading notes

---

package.json

Bump version to 8.1.0

---

UPGRADING.md
src/error.js

Fix DropboxResponseError class name in UPGRADING.md and add it's fields

---

src/auth.js
src/dropbox.js

 Fix refresh logic when no token expiration set

---

generator/typescript/index.d.tstemplate
src/auth.js
types/index.d.ts

- Fix for [#[447](https://github.com/dropbox/dropbox-sdk-js/issues/447)]
**Validation**

Fix return type for GetAccessTokenFromCode

---

examples/typescript/package-lock.json
package-lock.json
package.json
src/auth.js
test/build/browser.js
test/unit/auth.js
test/unit/dropbox.js
test/unit/response.js
test/unit/utils.js

Add unit testing for upload, download, rpc and different auth types

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
test/integration/team.js
test/integration/user.js

Integration tests

---

UPGRADING.md
examples/javascript/PKCE-backend/code_flow_example.js
examples/javascript/auth/index.html
examples/javascript/download/index.html
examples/javascript/simple-backend/code_flow_example.js
examples/javascript/team-as-user/index.html
examples/javascript/team/index.html
generator/generate_routes.py
generator/typescript/index.d.tstemplate
package-lock.json
package.json
src/auth.js
src/utils.js
test/unit/auth.js
types/index.d.ts

Allow PKCE flow for browser based apps

---

src/dropbox.js
test/integration/user.js
test/unit/dropbox.js

Allow SDK to perform multiauth

---

lib/routes.js
lib/types.js
types/dropbox_types.d.ts
types/index.d.ts

9303b45bbfa3d1d3de75a2da609ac47c179d18ba
Change Notes:
Auth Namespace:
- Update comments
Files Namespace:
- Update comments
Team Linked Apps Namespace:
- Update Examples
Team Log Generated Namespace:
- Update AdminRole union to include billing_admin

Spec Update

---

examples/javascript/pkce-browser/index.html

Update the pkce browser example to use correct function

---

package.json

Bump package version to address security updates

---

README.md

Case sensitivity was leading to a Github 404.
**Validation**

Fix broken link for PKCE browser

---

generator/typescript/index.d.tstemplate
package-lock.json
package.json
src/auth.js
src/dropbox.js
types/index.d.ts

Expose domain delimiter via main clients

---

package.json
src/constants.js
src/utils.js
test/unit/utils.js

Update configuration for custom hosts

---

UPGRADING.md
package.json
src/auth.js

Deprecate `authenticateWithCordova` function

---

.github/workflows/spec_update.yml

[Actions] Automatically Update Minor Version

---

.github/workflows/spec_update.yml

[Actions] Update minor bump action

---

package.json
src/utils.js
test/unit/utils.js

Fix baseApiUrl

---

generator/typescript/index.d.tstemplate
package.json
src/auth.js
src/dropbox.js
test/unit/auth.js
test/unit/dropbox.js
types/index.d.ts

Add customHeaders option to DropboxAuth

---

README.md

Fix TS links in README.md (#1126)
