src/dropbox-base.js, test/dropbox-base.js
Previously, if you set a custom RPC request handler, the `es6-promise` and `superagent` dependencies were still required and an exception would be thrown if they are missing during runtime. This change lazy-loads the default RPC request handler so errors won't be thrown about missing dependencies if the handler implementation is changed.
=> Lazy load rpc-request to avoid unnecessary dependencies

src/download-request.js, src/rpc-request.js, src/upload-request.js
This fixes the error cause when no response object was passed into the custom error building function. It will now have `text: undefined` when no response object is passed.
Fixes: #68
=> Handle errors where no response is received

generator/generate_routes.py, src/download-request.js, src/dropbox-base.js, src/get-base-url.js, src/routes-team.js, src/routes.js, src/rpc-request.js, src/upload-request.js, test/download-request.js, test/dropbox-base.js, test/dropbox-team.js, test/dropbox.js, test/rpc-request.js, test/upload-request.js
This makes longpoll work. It fixes #42 and #55.
=> Support hosts (e.g. notify) and auth (e.g. noauth)

src/download-request.js, src/http-header-safe-json.js, src/upload-request.js, test/download-request.js, test/upload-request.js
This PR fix issue #86 and it is based on response on dropbox forum https://www.dropboxforum.com/t5/API-support/HTTP-header-quot-Dropbox-API-Arg-quot-could-not-decode-input-as/m-p/195155#M8876 (posted by @MaxwellK in #86)
=> encode special characters in Dropbox-API-Arg

package.json
@braincore just realized this was broken because npm isn't linking back to GitHub.
=> Fix package.json repository url

.gitmodules
Using https://<url> instead of git@<url> will allow others to pull
in submodules without auth
=> Update submodule urls

docs/README.md
This simply fixes a broken link in the README :)
=> Fix broken link to authentication example in docs

src/rpc-request.js, test/rpc-request-error.js
This PR prevents the uncaught exceptions seen in #126 by attempting to `try`/`catch` the json parse.
I've added tests for the RPC error handling – one happy case where the errors are as expected (where the sdk was working fine) and one case where the thing being parsed was not valid json (the suspected cause of the crash).
I noticed that the fix to #108 was probably the where this bug was introduced, so while waiting for this to merge we're going to rollback to `v2.5.2`.
Cheers.
=> try/catch when parsing json in error responses, fixes #126

package.json
from https://github.com/dropbox/dropbox-sdk-js/issues/152 : 
es6-promise package was updated in version 4 to avoid overwriting global.Promise.
Simply updating the package.json to use the newer version of the package fixes the issue.
=> Updating es6-promise dependency

generator/typescript/dropbox_types.d.ts, generator/typescript/dropbox_types.d.tstemplate, package.json, src/download-request.js, src/dropbox-base.js, src/rpc-request.js, src/team/dropbox-team.js, src/upload-request.js, test/download-request.js, test/dropbox-base.js, test/rpc-request.js, test/upload-request.js, webpack-umd.config.js, webpack.config.js
This addresses issue #150.
Basically, it allows us to write code like this:
```js
const Dropbox = require('dropbox');
var dbx = new Dropbox({
// other options
proxy: 'http://proxy.acme.com:3128'
});
dbx.fileUploads({
}).then(results => {
// deal with results
}).catch(err => report);
```
In this example, the file upload will happen through an outbound proxy.
In this PR, I also added new unit tests to check the proxy settings and usage.
=> Add Support for Outbound Proxy

src/dropbox-base.js, test/dropbox-base.js
`redirect_uri` can be empty for `node.js` applications, as I understood from [docs](https://www.dropbox.com/developers/reference/oauth-guide):
> Note that for certain apps, such as command line and desktop apps, it's not possible for a web browser to redirect back to your app. In these cases, your app does not need to include a redirect_uri parameter. Dropbox will present the user with an authorization code that they will need to copy and paste into your app, at which point your app can exchange it for a reusable access toke
And such `url` will work as expected:
```
https://www.dropbox.com/oauth2/authorize?response_type=code&client_id={client_id}
```
So I added ability to not put `url` if there is no need for it.
=> Add ability to not place url in getAuthenticationUrl

generator/typescript/dropbox_types.d.ts, package.json
This PR adds the generation of typescript definition files to ensure they show up in distributed package.
When TypeScript definition files were introduced in https://github.com/dropbox/dropbox-sdk-js/pull/96, there was command added to the build step to ensure the `.d.ts` files are built.  See `&& npm run generate-tsds ` in [package.json line 15](https://github.com/jvilk/dropbox-sdk-js/blob/5eab745a91094f7dcaa04f796faa78b80bd47739/package.json#L15)
When RollUp was introduced in https://github.com/dropbox/dropbox-sdk-js/pull/137, `npm run generate-tsds` was now excluded from the build step.  This stops the `.d.ts` files from being generated and included in the package published to npm.
Without this PR, running `npm run build` creates the following files in the `dist/` directory:
``` …
```
=> Distribute .d.ts files as part of build step and fix .d.ts file

generator/typescript/dropbox_types.d.ts, generator/typescript/dropbox_types.d.tstemplate, src/rpc-request.js, test/rpc-request-error.js
We were seeing that when we had a folder that  exceeded ~70 files and called `filesListFolder` with the folder's path, the promise would never respond.
This is on a project that uses `isomorphic-fetch` to support dropbox sdk's fetch methods.
Digging into the problem, I found that it was the use of cloning the response from fetch by `parseBodyToType`.  When the response is sufficiently large, there is a known issue in `node_fetch` ( which is a dependency of `isomorphic-fetch` ) in which `clone` never responds, see https://github.com/bitinn/node-fetch/issues/396
The `.clone` was used to be able to re-read the stream as text in the case of `.json()` rejecting.  This happens when`.json()` rejects because the server responds with text instead of a JSON object.
We fix this by: instead of …
=> Fix issue where large response never resolves

README.md, docs/tutorials/Authentication.md, docs/tutorials/Installation.md, docs/tutorials/JavaScript SDK.md, examples/javascript/code_flow_example.js, package.json, rollup.config.js, src/download-request.js, src/dropbox-base.js, src/dropbox.js, src/rpc-request.js, src/upload-request.js, test/download-request.js, test/dropbox-base.js, test/dropbox-team.js, test/dropbox.js, test/rpc-request-error.js, test/rpc-request.js, test/upload-request.js
I assume we'll have some go-arounds on this PR so feedback and edits welcome! 😊
=> instantiate w fetch; warn deprecated global fetch

src/dropbox-base.js
We're using dropbox-sdk-js in a Cordova application but can't authorize because the InAppBrowser windows closes as an `-999` error is raised in iOS.
=> Fix iOS auth on cordova-plugin-inappbrowser

docs/README.md
Links were broken and returned a 404 since they pointed to non-existent HTML files.
This change updates the links to point to the actual Markdown files.
=> Fix "Tutorials" links in documentation

README.md
The link name "isormophic-fetch" in the Prerequisites section of
README.md has a minor typo (only the link's name has this typo, the
actual link is correct). It should've been "isomorphic" instead of
"isormophic" (the "r" is in the wrong place).
This change fixes that typo.
=> Fix minor typo "isormophic" in documentation

generator/typescript/dropbox_types.d.tstemplate
Added TypeScript definition for `authenticateWithCordova`.
This is extremely useful for users relying on `dropbox-sdk-js` in a Typescript environment.
=> Bugfix / Typescript outdated definition for authenticateWithCordova

src/auth.js
The fetch result is wrapped by `DropboxResponse` but `refreshAccessToken` didn't  access the returned data correctly 
**Validation**
=> Fix refreshAccessToken data accessing

release_notes.txt, scripts/release_note_generator.sh, scripts/update_version.sh, src/constants.js, src/response.js
- Change NO_AUTH constant from no_auth to noauth
- Throw errors instead of returning DropboxResponse with invalid status in response
- Add release_note_generator and update_version scripts
**Validation**
=> Fix noauth constant, Update error types, Add release scripts

src/response.js
This PR fixes the error which is actually thrown after the promise resolution
**Validation**
=> Fix: keep error in same async loop

.github/workflows/coverage.yml, .github/workflows/documentation.yml, .github/workflows/spec_update.yml, CONTRIBUTING.md, README.md, UPGRADING.md, examples/javascript/auth/index.html, examples/javascript/basic/index.html, examples/javascript/download/index.html, examples/javascript/team-as-user/index.html, examples/javascript/team/index.html, examples/javascript/upload/index.html, scripts/update_version.sh
=> Migrate references from master to main

src/auth.js, src/dropbox.js
Migrate logic from trying with require to checking for existence of window
**Validation**
=> Migrate node v window logic

README.md, examples/javascript/index.html, examples/javascript/pkce-browser/index.html, generator/typescript/index.d.tstemplate, package-lock.json, package.json, src/auth.js, test/unit/auth.js, types/index.d.ts
- Fix PKCE in browsers by addressing base 64 encoding difference between server and client
- Add Browser PKCE example first introduced in [#593](https://github.com/dropbox/dropbox-sdk-js/pull/593)
- Uses window.sessionStorage for redirect handling
- Add node validation tests for PKCE
- Add new `setCodeVerifier` and `getCodeVerifier` methods to handle state between redirects
- Break generation of code verifier and code challenge to allow for easier testing with hard coded values
=> Fix PKCE for browsers and add example

generator/typescript/index.d.tstemplate, package.json, src/auth.js, src/constants.js, src/dropbox.js, src/utils.js, test/unit/auth.js, test/unit/utils.js, types/index.d.ts
- Add ability to pass in custom domains to Dropbox and DropboxAuth objects
- Refactor url generation to function based on hosts
**Validation**
=> Add support for custom domains

src/dropbox.js
Small change to use the `fetch` function that was set in the contstructor:
```
this.fetch = options.fetch || fetch;
```
instead of the global fetch defined at the top of the file.
This fixes an issue where a custom fetch function was passed into the dropbox constructor, but here it was still using the wrong fetch.
Note: `npm run lint` does not pass, but it was not passing before either, this PR does not introduce any new lint warnings/errors.
**Validation**
=> use fetch function defined in the class property, instead of the global one

generator/typescript/index.d.tstemplate, package.json, src/constants.js, src/dropbox.js, test/unit/dropbox.js, types/index.d.ts
=> Add cookie auth and custom header feature

generator/typescript/index.d.tstemplate, src/auth.js, test/unit/auth.js, types/index.d.ts
When refreshing authorization access token, send the end point parameters via body instead of URL.
This prevents intermediate proxies or logs to accidentally (or not) expose secret values.
Fix #813
**Validation**
=> feat(auth): refresh access token request using body params

generator/generate_routes.py, lib/routes.js, src/dropbox.js, types/index.d.ts
Update js and ts to include route scopes in their doc strings.
**Validation**
(seems to error on examples which rely on packages that are not installed?)
=> Add scopes to JS and TS docs

.github/workflows/ci.yml
=> make ci runnable from main

package-lock.json, package.json, src/auth.js, src/utils.js, test/unit/auth.js, test/unit/utils.js
When running the current version of Dropbox SDK in a service worker environment, `fetch` and `crypto` API will make issues.
The root cause of the issues is that service worker uses its own global space than that of browsers and NodeJS envs. Hence, in this PR, a function `isWorkerEnv` is introduced, and if SDK runs on a service worker, `fetch` and `crypto` API is fetched from the worker's global space.
**Validation**
=> Dropbox SDK is now aware of the service worker environment

lib/routes.js, lib/types.js, package-lock.json, package.json, types/dropbox_types.d.ts, types/index.d.ts
Automated Spec Update 
69f7bb2ea7702db5564f12549efb23956c5d6329 
Change Notes:
files Namespace
- Update examples
shared_links Namespace
- Update get_shared_link_metadata route to include app and user auth
team_folders Namespace
- Update team_folder/create, team_folder/rename, team_folder/list, team_folder/list/continue, team_folder/get_info, team_folder/activate, team_folder/archive, team_folder/archive/check, team_folder/permanently_delete, team_folder/update_sync_settings routes to include updated scopes
team_legal_holds Namespace
- Update legal_holds/create_policy, legal_holds/get_policy, legal_holds/list_policies, legal_holds/list_held_revisions, legal_holds/list_held_revisions_continue, legal_holds/update_policy, legal_holds/release_policy routes to include updated scopes …
=> Automated Spec Update
